<?php

namespace App\Controller;

use Cake\Controller\ComponentRegistry;
use Cake\Event\EventInterface;
use Cake\Event\EventManagerInterface;
use Cake\Http\Response;
use Cake\Http\ServerRequest;

class AdminController extends AppController {

    public function initialize(): void {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout("admin");
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index() {
    }

    public function newPost() {
    }

}
